### ISSUE TITLE
csv2pjson_public.py unicode error

### ISSUE THREAD

**Issue by Germanaz0** [HHSIDEAlab/provider-data-tools#21]
While loading the command `loadnppes.py` and while creating the pjson files I am getting the following error:

```
113000 files created. Total time is 150.392736912 seconds.
Traceback (most recent call last):
  File "/usr/local/bin/csv2pjson_public.py", line 4, in <module>
    __import__('pkg_resources').run_script('pdt==0.8.2.3', 'csv2pjson_public.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/pdt-0.8.2.3-py2.7.egg/EGG-INFO/scripts/csv2pjson_public.py", line 535, in <module>
    result = publiccsv2pjson(csv_file, output_dir)
  File "/usr/local/lib/python2.7/site-packages/pdt-0.8.2.3-py2.7.egg/EGG-INFO/scripts/csv2pjson_public.py", line 179, in publiccsv2pjson
    row[i] = six.u(row[i])
  File "/usr/local/lib/python2.7/site-packages/six.py", line 647, in u
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
UnicodeDecodeError: 'unicodeescape' codec can't decode byte 0x5c in position 9: \ at end of string
```

Just after this error, it starts fetching the fhir json without any error.

What is the main issue ?

**Comment by Germanaz0** [comment]
I had python 2.7.7 updated to 3.3.6 and now it seems to work properly, but on README says that it should be compatible with my previous version...

**Comment by aviars** [comment]
I'll look into it. Yes it should work on 2.7.

Best,

Alan
